//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public int id { get; set; }
        public Nullable<int> id_customer { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> estimatedDeliveryDate { get; set; }
        public Nullable<double> total { get; set; }
    
        public virtual user user { get; set; }
    }
}
